#!/usr/bin/env python3
"""
Generate curriculum/open.md — a committed snapshot of the Verification Debt ledger.

The ledger is the issue tracker (see #5). This script is a read-through cache: it
makes a clone of the repository self-contained and puts debt history into `git log`,
where it can be read without an API call. The tracker stays authoritative. If the
snapshot and the tracker disagree, the tracker is right and the snapshot is stale.

Usage:
    python tools/snapshot_debt.py            # write curriculum/open.md
    python tools/snapshot_debt.py --check    # exit 1 if stale (for CI)

Requires the `gh` CLI, authenticated.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "curriculum" / "open.md"

HEADER = """\
<!-- GENERATED by tools/snapshot_debt.py — do not edit.
     The ledger is the issue tracker; this file is a committed snapshot of it.
     Regenerate with: python tools/snapshot_debt.py -->

# Verification Debt — open

Snapshot of [`label:debt:open`]({query}) taken {when}.

The tracker is the source of truth. This file exists so that a clone of the
repository contains the programme's debt, and so `git log` can answer what the
programme owed on a given date. See [`README.md`](README.md).

"""


def gh_issues(label: str) -> list[dict]:
    out = subprocess.run(
        [
            "gh", "issue", "list",
            "--label", label,
            "--state", "all",
            "--limit", "200",
            "--json", "number,title,state,body,url",
        ],
        capture_output=True,
        text=True,
        encoding="utf-8",  # gh emits UTF-8; Windows would otherwise decode as cp1252
        cwd=ROOT,
    )
    if out.returncode != 0:
        sys.exit(f"gh failed: {out.stderr.strip()}")
    return sorted(json.loads(out.stdout), key=lambda i: i["number"])


def link_text(title: str) -> str:
    """Issue titles start with '[debt] ...'; bare brackets break a markdown link."""
    return title.replace("[", "\\[").replace("]", "\\]")


def field(body: str, marker: str) -> str:
    """Pull a one-line field out of an issue body, e.g. '**Holds down.** ...'."""
    for line in body.splitlines():
        if line.strip().startswith(marker):
            return line.split(marker, 1)[1].strip()
    return "—"


def section(body: str, heading: str) -> str:
    lines, grab, out = body.splitlines(), False, []
    for line in lines:
        if line.strip().lower() == f"## {heading}".lower():
            grab = True
            continue
        if grab and line.startswith("## "):
            break
        if grab and line.strip():
            out.append(line.strip())
    return " ".join(out) or "—"


def render(issues: list[dict]) -> str:
    query = "https://github.com/NGL321/mosaic/issues?q=is%3Aissue+label%3Adebt%3Aopen"
    parts = [HEADER.format(query=query, when=date.today().isoformat())]

    live = [i for i in issues if i["state"].upper() == "OPEN"]
    done = [i for i in issues if i["state"].upper() != "OPEN"]

    parts.append(f"**{len(live)} open · {len(done)} discharged**\n")
    parts.append("| # | holds down | curriculum |")
    parts.append("|---|---|---|")
    for i in live:
        holds = field(i["body"], "**Holds down.**")
        curr = section(i["body"], "Curriculum")
        parts.append(f"| [#{i['number']}]({i['url']}) | {holds} | {curr} |")

    parts.append("\n---\n")
    for i in live:
        parts.append(f"### [#{i['number']} — {link_text(i['title'])}]({i['url']})\n")
        parts.append(f"**Holds down.** {field(i['body'], '**Holds down.**')}\n")
        parts.append(f"**Discharged by.** {section(i['body'], 'Discharged by')}\n")
        parts.append(f"**Curriculum.** {section(i['body'], 'Curriculum')}\n")

    if done:
        parts.append("## Discharged\n")
        for i in done:
            parts.append(f"- [#{i['number']} — {link_text(i['title'])}]({i['url']})")

    return "\n".join(parts) + "\n"


def main() -> None:
    text = render(gh_issues("debt:open") + gh_issues("debt:discharged"))
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        # The snapshot date changes daily; compare everything else.
        strip = lambda s: "\n".join(  # noqa: E731
            ln for ln in s.splitlines() if not ln.startswith("Snapshot of")
        )
        if strip(current) != strip(text):
            sys.exit("curriculum/open.md is stale — run: python tools/snapshot_debt.py")
        print("curriculum/open.md is current")
        return
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
