#!/usr/bin/env python3
"""
Generate curriculum/open.md — a committed snapshot of the Verification Debt ledger.

The ledger is the issue tracker (see #5). This script is a read-through cache: it
makes a clone of the repository self-contained and puts debt history into `git log`,
where it can be read without an API call. The tracker stays authoritative. If the
snapshot and the tracker disagree, the tracker is right and the snapshot is stale.

The **label** is the axis, not the issue state — `curriculum/README.md` declares it
so and the snapshot header says so. State is cross-checked against it and any
disagreement is reported rather than silently filed, because this file is an
auditable artifact and a plausible-looking wrong row is worse than a loud failure.

Usage:
    python tools/snapshot_debt.py            # write curriculum/open.md
    python tools/snapshot_debt.py --check    # verify it is current (for CI)

Exit codes (distinct so CI can tell "regenerate this" from "the tool is broken"):
    0  fine
    1  --check: the snapshot is stale; regenerate it
    2  the tool could not run — gh missing, unauthenticated, bad JSON
    3  the tracker data is malformed — an issue is missing required fields

Requires the `gh` CLI, authenticated.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

# Messages carry em dashes; a cp1252 console would mangle them in the CI log.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):
        pass

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "curriculum" / "open.md"

OPEN_LABEL = "debt:open"
DONE_LABEL = "debt:discharged"
QUERY = "https://github.com/NGL321/mosaic/issues?q=is%3Aissue+label%3Adebt%3Aopen"

EXIT_OK, EXIT_STALE, EXIT_TOOL, EXIT_MALFORMED = 0, 1, 2, 3

HEADER = """\
<!-- GENERATED by tools/snapshot_debt.py — do not edit.
     The ledger is the issue tracker; this file is a committed snapshot of it.
     Regenerate with: python tools/snapshot_debt.py -->

# Verification Debt — open

Snapshot of [`label:debt:open`]({query}) taken {when}. Rows are grouped by **label**,
which is authoritative; see [`README.md`](README.md).

The tracker is the source of truth. This file exists so that a clone of the
repository contains the programme's debt, and so `git log` can answer what the
programme owed on a given date.

"""

_problems: list[str] = []


def warn(msg: str) -> None:
    _problems.append(msg)
    print(f"warning: {msg}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Fetching
# ---------------------------------------------------------------------------


def gh_issues(*labels: str) -> list[dict]:
    """Fetch issues carrying any of `labels`, deduplicated by number."""
    seen: dict[int, dict] = {}
    for label in labels:
        try:
            out = subprocess.run(
                [
                    "gh", "issue", "list",
                    "--label", label,
                    "--state", "all",
                    "--limit", "200",
                    "--json", "number,title,state,body,url,labels",
                ],
                capture_output=True,
                text=True,
                encoding="utf-8",  # gh emits UTF-8; Windows would decode as cp1252
                cwd=ROOT,
            )
        except FileNotFoundError:
            sys.exit(EXIT_TOOL)
        if out.returncode != 0:
            print(f"gh failed: {out.stderr.strip()}", file=sys.stderr)
            sys.exit(EXIT_TOOL)
        try:
            batch = json.loads(out.stdout)
        except json.JSONDecodeError as e:
            print(f"gh returned unparseable JSON: {e}", file=sys.stderr)
            sys.exit(EXIT_TOOL)
        # An issue carrying both labels is fetched twice; keep it once.
        for issue in batch:
            seen[issue["number"]] = issue
    return sorted(seen.values(), key=lambda i: i["number"])


# ---------------------------------------------------------------------------
# Parsing issue bodies
# ---------------------------------------------------------------------------


def field(body: str, marker: str, *, where: str = "") -> str:
    """Pull a one-line field out of an issue body, e.g. '**Holds down.** ...'."""
    for line in body.splitlines():
        if line.strip().startswith(marker):
            return line.split(marker, 1)[1].strip()
    warn(f"{where}: missing field {marker!r}")
    return "—"


def section(body: str, heading: str, *, where: str = "") -> str:
    """
    Return the body of a '## <heading>' section with its line structure intact.

    Joining with a space would collapse a bullet list into '- foo - bar'. Every
    issue body happens to be single-line today; that is not a property to rely on.
    """
    grab, out = False, []
    for line in body.splitlines():
        if line.strip().lower() == f"## {heading}".lower():
            grab = True
            continue
        if grab and line.startswith("## "):
            break
        if grab:
            out.append(line.rstrip())
    text = "\n".join(out).strip()
    if not text:
        warn(f"{where}: missing or empty section '## {heading}'")
        return "—"
    return text


def cell(text: str) -> str:
    """Flatten and escape a value for use inside a markdown table cell."""
    flat = " ".join(line.strip() for line in text.splitlines() if line.strip())
    return flat.replace("|", "\\|")


def link_text(title: str) -> str:
    """Issue titles start with '[debt] ...'; bare brackets break a markdown link."""
    return title.replace("[", "\\[").replace("]", "\\]")


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def partition(issues: list[dict]) -> tuple[list[dict], list[dict]]:
    """
    Split on the **label**, which is authoritative, and cross-check state.

    A closed issue still labelled `debt:open`, or an open one labelled
    `debt:discharged`, is a bookkeeping error. It is reported, not quietly filed
    under whichever heading the state happens to imply.
    """
    live, done = [], []
    for i in issues:
        names = {lbl["name"] for lbl in i.get("labels", [])}
        is_open_state = i["state"].upper() == "OPEN"
        ref = f"#{i['number']}"

        if OPEN_LABEL in names and DONE_LABEL in names:
            warn(f"{ref}: carries both {OPEN_LABEL} and {DONE_LABEL}; filing as open")
            names.discard(DONE_LABEL)

        if OPEN_LABEL in names:
            if not is_open_state:
                warn(f"{ref}: labelled {OPEN_LABEL} but the issue is closed")
            live.append(i)
        elif DONE_LABEL in names:
            if is_open_state:
                warn(f"{ref}: labelled {DONE_LABEL} but the issue is still open")
            done.append(i)
        else:
            warn(f"{ref}: carries neither debt label; skipped")
    return live, done


def render(issues: list[dict]) -> str:
    live, done = partition(issues)
    parts = [HEADER.format(query=QUERY, when=date.today().isoformat())]
    parts.append(f"**{len(live)} open · {len(done)} discharged**\n")
    parts.append("| # | holds down | curriculum |")
    parts.append("|---|---|---|")
    for i in live:
        ref = f"#{i['number']}"
        holds = cell(field(i["body"], "**Holds down.**", where=ref))
        curr = cell(section(i["body"], "Curriculum", where=ref))
        parts.append(f"| [{ref}]({i['url']}) | {holds} | {curr} |")

    parts.append("\n---\n")
    for i in live:
        ref = f"#{i['number']}"
        parts.append(f"### [{ref} — {link_text(i['title'])}]({i['url']})\n")
        parts.append(f"**Holds down.** {field(i['body'], '**Holds down.**', where=ref)}\n")
        parts.append(f"**Discharged by.** {section(i['body'], 'Discharged by', where=ref)}\n")
        parts.append(f"**Curriculum.** {section(i['body'], 'Curriculum', where=ref)}\n")

    if done:
        parts.append("## Discharged\n")
        for i in done:
            parts.append(f"- [#{i['number']} — {link_text(i['title'])}]({i['url']})")

    return "\n".join(parts) + "\n"


def _comparable(text: str) -> str:
    """Everything but the snapshot date, which changes daily and means nothing."""
    return "\n".join(ln for ln in text.splitlines() if not ln.startswith("Snapshot of"))


def main() -> None:
    text = render(gh_issues(OPEN_LABEL, DONE_LABEL))

    if _problems:
        print(
            f"\n{len(_problems)} problem(s) in the tracker data — the snapshot above "
            f"is not trustworthy until they are fixed.",
            file=sys.stderr,
        )

    if "--check" in sys.argv:
        if _problems:
            sys.exit(EXIT_MALFORMED)
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if _comparable(current) != _comparable(text):
            print(
                "curriculum/open.md is stale — run: python tools/snapshot_debt.py",
                file=sys.stderr,
            )
            sys.exit(EXIT_STALE)
        print("curriculum/open.md is current")
        return

    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    if _problems:
        sys.exit(EXIT_MALFORMED)


if __name__ == "__main__":
    main()
